AllCops:
  TargetRubyVersion: 3.0.0

Layout/LineLength:
  Max: 180

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods:
    - 'describe'
    - 'context'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes